### ISSUE TITLE
Crashing on IDA 6.7

### ISSUE THREAD

**Issue by swackhamer** [deresz/funcap#11]
Crashes almost immediately after hooking a segment and running the debugger.  Have tried multiple executables that work well with IDA 6.6 but crash almost immediately on 6.7.  Can give a crash dump on request.

Using IDA Pro 6.7.141229 32bit

Commands executed: d.on(); d.hookSeg(".text")

**Comment by deresz** [comment]
ok, will diagnose it as soon as I have 6.7

**Comment by deresz** [comment]
It seems to be a problem with Python debug hooks in IDA 6.7. I will contact Hex-Rays.

**Comment by deresz** [comment]
Ok confirmed as a bug with Hex-Rays. You can contact Hex-Rays support for a fix. IDA 6.8 should contain an official fix.
